spring.application.name=CacheAndRateLimmiter

spring.cache.type=redis
#spring.data.redis.host=localhost
spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.ssl.enabled=false